name: _

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml
    permissions: write-all
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions: write-all
