name: Push Checks

on:
  push:
  pull_request:
    types:
      - opened

jobs:
  check-and-build:
    name: Check and Build
    uses: ./.github/workflows/check-and-build.yml
    permissions: write-all
