# Kinda based by https://github.com/myrotvorets/set-commit-status-action/actions/runs/12344741285/workflow
name: Push Checks

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-and-build:
    name: Check and Build
    uses: ./.github/workflows/check-and-build.yml
    permissions: write-all
